ccf-cose-endorsement-tagged = #6.18(ccf-cose-endorsement)

ccf-cose-endorsement = [
  phdr : bstr .cbor protected_headers,                     ; bstr-wrapped protected headers
  uhdr : unprotected_headers,                              ; no unprotected headers included
  payload : bstr,                                          ; previous servide identity public key
  signature : bstr                                         ; COSE-signature
]

unprotected_headers = {
  ; empty map instead of 'nil'. QCBOR library verifier doesn't support 'nil'.
}

protected_headers = {
  &(alg: 1) => int,                                        ; signing algoritm ID, as per RFC8152
  &(cwt: 15) => cwt_map,                                   ; CWT claims, as per RFC8392
  &(ccf: "ccf.v1") => ccf_map                              ; a set of CCF-specific parameters
}

cwt_map = {
  &(iat: 6) => int                                         ; "issued at", number of seconds since the epoch
}

ccf_map = {
  &(endorsed_from: "epoch.start.txid") => tstr,            ; first committed TxID in the endorsed epoch
  ? &(endorsed_to: "epoch.end.txid") => tstr,              ; last committed TxID in the endorsed epoch
  ? &(last_endorsed_root: "merkle.root") => bstr .size 32  ; Merkle tree root of the last TxID in the endorsed epoch (string of HASH_SIZE(32) bytes)
}
