ccf-cose-root-signature-tagged = #6.18(ccf-cose-root-signature)

ccf-cose-root-signature = [
  phdr : bstr .cbor protected_headers,
  uhdr : unprotected_headers,
  payload : nil,
  signature : bstr
]

unprotected_headers = {
  ; empty map
}

protected_headers = {
  &(alg: 1) => int,
  &(kid: 4) => bstr,
  &(cwt: 15) => cwt_map,
  &(vds: 395) => int,
  "ccf.v1" => ccf_map
}

cwt_map = {
  &(iat: 6) => int
}

ccf_map = {
  &(last_signed_txid: "txid") => tstr
}
