# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor_registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65xecutor_registration.proto\x12\x03\x63\x63\x66\"\x9e\x01\n\x0b\x41ttestation\x12\'\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x17.ccf.Attestation.Format\x12\r\n\x05quote\x18\x02 \x01(\x0c\x12\x14\n\x0c\x65ndorsements\x18\x03 \x01(\x0c\"A\n\x06\x46ormat\x12\r\n\tOE_SGX_V1\x10\x00\x12\x14\n\x10INSECURE_VIRTUAL\x10\x01\x12\x12\n\x0e\x41MD_SEV_SNP_V1\x10\x02\"\xa9\x01\n\x0bNewExecutor\x12%\n\x0b\x61ttestation\x18\x01 \x01(\x0b\x32\x10.ccf.Attestation\x12\x0c\n\x04\x63\x65rt\x18\x02 \x01(\x0c\x12\x39\n\x13supported_endpoints\x18\x03 \x03(\x0b\x32\x1c.ccf.NewExecutor.EndpointKey\x1a*\n\x0b\x45ndpointKey\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\"\xd5\x01\n\x12RegistrationResult\x12\x30\n\x07outcome\x18\x01 \x01(\x0e\x32\x1f.ccf.RegistrationResult.Outcome\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"|\n\x07Outcome\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12$\n ATTESTATION_VERIFICATION_FAILURE\x10\x01\x12\x1b\n\x17MEASUREMENT_NOT_TRUSTED\x10\x02\x12\x12\n\x0e\x44UPLICATE_CERT\x10\x03\x12\x0c\n\x08REJECTED\x10\x04\x32W\n\x14\x45xecutorRegistration\x12?\n\x10RegisterExecutor\x12\x10.ccf.NewExecutor\x1a\x17.ccf.RegistrationResult\"\x00\x42\x02H\x03\x62\x06proto3')



_ATTESTATION = DESCRIPTOR.message_types_by_name['Attestation']
_NEWEXECUTOR = DESCRIPTOR.message_types_by_name['NewExecutor']
_NEWEXECUTOR_ENDPOINTKEY = _NEWEXECUTOR.nested_types_by_name['EndpointKey']
_REGISTRATIONRESULT = DESCRIPTOR.message_types_by_name['RegistrationResult']
_ATTESTATION_FORMAT = _ATTESTATION.enum_types_by_name['Format']
_REGISTRATIONRESULT_OUTCOME = _REGISTRATIONRESULT.enum_types_by_name['Outcome']
Attestation = _reflection.GeneratedProtocolMessageType('Attestation', (_message.Message,), {
  'DESCRIPTOR' : _ATTESTATION,
  '__module__' : 'executor_registration_pb2'
  # @@protoc_insertion_point(class_scope:ccf.Attestation)
  })
_sym_db.RegisterMessage(Attestation)

NewExecutor = _reflection.GeneratedProtocolMessageType('NewExecutor', (_message.Message,), {

  'EndpointKey' : _reflection.GeneratedProtocolMessageType('EndpointKey', (_message.Message,), {
    'DESCRIPTOR' : _NEWEXECUTOR_ENDPOINTKEY,
    '__module__' : 'executor_registration_pb2'
    # @@protoc_insertion_point(class_scope:ccf.NewExecutor.EndpointKey)
    })
  ,
  'DESCRIPTOR' : _NEWEXECUTOR,
  '__module__' : 'executor_registration_pb2'
  # @@protoc_insertion_point(class_scope:ccf.NewExecutor)
  })
_sym_db.RegisterMessage(NewExecutor)
_sym_db.RegisterMessage(NewExecutor.EndpointKey)

RegistrationResult = _reflection.GeneratedProtocolMessageType('RegistrationResult', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONRESULT,
  '__module__' : 'executor_registration_pb2'
  # @@protoc_insertion_point(class_scope:ccf.RegistrationResult)
  })
_sym_db.RegisterMessage(RegistrationResult)

_EXECUTORREGISTRATION = DESCRIPTOR.services_by_name['ExecutorRegistration']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ATTESTATION._serialized_start=37
  _ATTESTATION._serialized_end=195
  _ATTESTATION_FORMAT._serialized_start=130
  _ATTESTATION_FORMAT._serialized_end=195
  _NEWEXECUTOR._serialized_start=198
  _NEWEXECUTOR._serialized_end=367
  _NEWEXECUTOR_ENDPOINTKEY._serialized_start=325
  _NEWEXECUTOR_ENDPOINTKEY._serialized_end=367
  _REGISTRATIONRESULT._serialized_start=370
  _REGISTRATIONRESULT._serialized_end=583
  _REGISTRATIONRESULT_OUTCOME._serialized_start=459
  _REGISTRATIONRESULT_OUTCOME._serialized_end=583
  _EXECUTORREGISTRATION._serialized_start=585
  _EXECUTORREGISTRATION._serialized_end=672
# @@protoc_insertion_point(module_scope)
