# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x03\x63\x63\x66\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x06Header\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"]\n\x12RequestDescription\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x1c\n\x07headers\x18\x03 \x03(\x0b\x32\x0b.ccf.Header\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\"\x18\n\x07KVTable\x12\r\n\x05table\x18\x01 \x01(\t\"#\n\x05KVKey\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"7\n\nKVKeyValue\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x18\n\x07KVValue\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x1e\n\x0bKVHasResult\x12\x0f\n\x07present\x18\x01 \x01(\x08\"\x1c\n\tKVVersion\x12\x0f\n\x07version\x18\x01 \x01(\x04\"V\n\x13ResponseDescription\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12\x1c\n\x07headers\x18\x02 \x03(\x0b\x32\x0b.ccf.Header\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x32\x86\x03\n\x02KV\x12>\n\x07StartTx\x12\x16.google.protobuf.Empty\x1a\x17.ccf.RequestDescription\"\x00\x30\x01\x12;\n\x05\x45ndTx\x12\x18.ccf.ResponseDescription\x1a\x16.google.protobuf.Empty\"\x00\x12!\n\x03Get\x12\n.ccf.KVKey\x1a\x0c.ccf.KVValue\"\x00\x12%\n\x03Has\x12\n.ccf.KVKey\x1a\x10.ccf.KVHasResult\"\x00\x12*\n\nGetVersion\x12\n.ccf.KVKey\x1a\x0e.ccf.KVVersion\"\x00\x12\x30\n\x03Put\x12\x0f.ccf.KVKeyValue\x1a\x16.google.protobuf.Empty\"\x00\x12.\n\x06\x44\x65lete\x12\n.ccf.KVKey\x1a\x16.google.protobuf.Empty\"\x00\x12+\n\x06GetAll\x12\x0c.ccf.KVTable\x1a\x0f.ccf.KVKeyValue\"\x00\x30\x01\x42\x02H\x03\x62\x06proto3')



_HEADER = DESCRIPTOR.message_types_by_name['Header']
_REQUESTDESCRIPTION = DESCRIPTOR.message_types_by_name['RequestDescription']
_KVTABLE = DESCRIPTOR.message_types_by_name['KVTable']
_KVKEY = DESCRIPTOR.message_types_by_name['KVKey']
_KVKEYVALUE = DESCRIPTOR.message_types_by_name['KVKeyValue']
_KVVALUE = DESCRIPTOR.message_types_by_name['KVValue']
_KVHASRESULT = DESCRIPTOR.message_types_by_name['KVHasResult']
_KVVERSION = DESCRIPTOR.message_types_by_name['KVVersion']
_RESPONSEDESCRIPTION = DESCRIPTOR.message_types_by_name['ResponseDescription']
Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.Header)
  })
_sym_db.RegisterMessage(Header)

RequestDescription = _reflection.GeneratedProtocolMessageType('RequestDescription', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDESCRIPTION,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.RequestDescription)
  })
_sym_db.RegisterMessage(RequestDescription)

KVTable = _reflection.GeneratedProtocolMessageType('KVTable', (_message.Message,), {
  'DESCRIPTOR' : _KVTABLE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.KVTable)
  })
_sym_db.RegisterMessage(KVTable)

KVKey = _reflection.GeneratedProtocolMessageType('KVKey', (_message.Message,), {
  'DESCRIPTOR' : _KVKEY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.KVKey)
  })
_sym_db.RegisterMessage(KVKey)

KVKeyValue = _reflection.GeneratedProtocolMessageType('KVKeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KVKEYVALUE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.KVKeyValue)
  })
_sym_db.RegisterMessage(KVKeyValue)

KVValue = _reflection.GeneratedProtocolMessageType('KVValue', (_message.Message,), {
  'DESCRIPTOR' : _KVVALUE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.KVValue)
  })
_sym_db.RegisterMessage(KVValue)

KVHasResult = _reflection.GeneratedProtocolMessageType('KVHasResult', (_message.Message,), {
  'DESCRIPTOR' : _KVHASRESULT,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.KVHasResult)
  })
_sym_db.RegisterMessage(KVHasResult)

KVVersion = _reflection.GeneratedProtocolMessageType('KVVersion', (_message.Message,), {
  'DESCRIPTOR' : _KVVERSION,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.KVVersion)
  })
_sym_db.RegisterMessage(KVVersion)

ResponseDescription = _reflection.GeneratedProtocolMessageType('ResponseDescription', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDESCRIPTION,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:ccf.ResponseDescription)
  })
_sym_db.RegisterMessage(ResponseDescription)

_KV = DESCRIPTOR.services_by_name['KV']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _HEADER._serialized_start=46
  _HEADER._serialized_end=84
  _REQUESTDESCRIPTION._serialized_start=86
  _REQUESTDESCRIPTION._serialized_end=179
  _KVTABLE._serialized_start=181
  _KVTABLE._serialized_end=205
  _KVKEY._serialized_start=207
  _KVKEY._serialized_end=242
  _KVKEYVALUE._serialized_start=244
  _KVKEYVALUE._serialized_end=299
  _KVVALUE._serialized_start=301
  _KVVALUE._serialized_end=325
  _KVHASRESULT._serialized_start=327
  _KVHASRESULT._serialized_end=357
  _KVVERSION._serialized_start=359
  _KVVERSION._serialized_end=387
  _RESPONSEDESCRIPTION._serialized_start=389
  _RESPONSEDESCRIPTION._serialized_end=475
  _KV._serialized_start=478
  _KV._serialized_end=868
# @@protoc_insertion_point(module_scope)
