workspace: "/tmp/"
debs:
  - apt-transport-https
  - ninja-build
  - libuv1-dev
  - python3.7-dev
  - python3.7-venv
  - libc++-9-dev
  - libc++abi-9-dev
  - llvm-9
  - clang-9
  - libc++-8-dev
  - libc++abi-8-dev
  - llvm-8
  - clang-8
  - expect
  - xsltproc
  - git
  - libcurl4-openssl-dev
  - ccache
  - doxygen
mbedtls_ver: "2.16.2"
mbedtls_dir: "mbedtls-{{ mbedtls_ver }}"
mbedtls_src: "{{ mbedtls_dir }}.tar.gz"
fb_ver: "1.11.0"
flatbuffers_src: "flatbuffers-{{ fb_ver }}.tar.gz"
flatbuffers_url: "https://codeload.github.com/google/flatbuffers/tar.gz/1.11.0"
fb_prefix: "/opt/flatbuffers"
