- name: Include vars
  include_vars: common.yml

- name: Install Open Enclave
  apt:
    deb: "{{ oe_deb }}"
  become: true

- name: Make OE LVI dir
  file:
    path: "{{ oe_lvi_bin_dir }}"
    state: directory
  become: true

- name: Copy invoke_compiler to OE LVI dir
  copy:
    remote_src: true
    src: "{{ oe_lvi_scripts_dir }}/invoke_compiler"
    dest: "{{ oe_lvi_bin_dir }}/invoke_compiler"
    mode: preserve
  become: true

- name: Create OE LVI symlink to clang-8
  file:
    src: /usr/bin/clang-8
    dest: "{{ oe_lvi_bin_dir }}/clang-8_symlink"
    state: link
  become: true

- name: Generate OE LVI wrapper for clang-8
  shell: |
    "{{ oe_lvi_scripts_dir }}/generate_wrapper" --name=clang-8 --path="{{ oe_lvi_bin_dir }}"
  args:
    chdir: "{{ oe_lvi_bin_dir }}"
  become: true

- name: Create OE LVI symlink to clang++-8
  file:
    src: /usr/bin/clang++-8
    dest: "{{ oe_lvi_bin_dir }}/clang++-8_symlink"
    state: link
  become: true

- name: Generate OE LVI wrapper for clang++-8
  shell: |
    "{{ oe_lvi_scripts_dir }}/generate_wrapper" --name=clang++-8 --path="{{ oe_lvi_bin_dir }}"
  args:
    chdir: "{{ oe_lvi_bin_dir }}"
  become: true

- name: Download Intel LVI toolset
  get_url:
    url: "{{ oe_lvi_intel_bin_url }}"
    dest: "{{ workspace }}/{{ oe_lvi_toolset_name }}"

- name: Remove existing expanded Intel LVI toolset
  file:
    path: "{{ workspace }}/external"
    state: absent

- name: Expand Intel LVI toolset
  unarchive:
    src: "{{ workspace }}/{{ oe_lvi_toolset_name }}"
    dest: "{{ workspace }}"
    copy: no
    creates: "{{ workspace }}/external/toolset"

- name: Copy Intel LVI as
  copy:
    remote_src: true
    src: "{{ workspace }}/external/toolset/as"
    dest: "{{ oe_lvi_bin_dir }}/as"
    mode: preserve
  become: true

- name: Copy Intel LVI ld
  copy:
    remote_src: true
    src: "{{ workspace }}/external/toolset/ld"
    dest: "{{ oe_lvi_bin_dir }}/ld"
    mode: preserve
  become: true

# TODO: Download specific as and ld