FROM ubuntu:18.04

RUN echo "APT::Acquire::Retries \"5\";" | tee /etc/apt/apt.conf.d/80-retries

# Work-around for https://github.com/intel/linux-sgx/issues/395
RUN mkdir -p /etc/init

COPY getting_started/setup_vm/ /setup_vm/
RUN apt update && apt install -y ansible software-properties-common
RUN cd setup_vm; ansible-playbook -i local_nodriver *.yml

# Necessary to publish performance data
RUN apt install azure-cli