name: "Crypto CI"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-crypto-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  native:
    name: Native ${{ matrix.backend.name }} backend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - name: OpenSSL
            features: crypto_openssl
          - name: pure-Rust
            features: crypto_pure_rust

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Build with ${{ matrix.backend.name }} backend
        run: cargo build --manifest-path crypto/Cargo.toml --no-default-features --features "${{ matrix.backend.features }}"

      - name: Test with ${{ matrix.backend.name }} backend
        run: cargo test --manifest-path crypto/Cargo.toml --no-default-features --features "${{ matrix.backend.features }}" -- --nocapture

  wasm:
    name: WASM ${{ matrix.backend.name }} backend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - name: WebCrypto
            features: crypto_webcrypto
          - name: pure-Rust
            features: crypto_pure_rust

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Setup WASM tooling
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack --version 0.13.1 --locked

      - name: Check ${{ matrix.backend.name }} backend
        run: cargo check --manifest-path crypto/Cargo.toml --target wasm32-unknown-unknown --no-default-features --features "${{ matrix.backend.features }}"

      - name: Test ${{ matrix.backend.name }} backend
        working-directory: crypto
        run: wasm-pack test --node --no-default-features --features "${{ matrix.backend.features }}"
