name: "COSE CI"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-cose-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  native:
    name: Native build and test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Build native with pure-Rust backend
        run: cargo build --manifest-path cose/Cargo.toml --no-default-features --features "crypto_pure_rust"

      - name: Test native with pure-Rust backend
        run: cargo test --manifest-path cose/Cargo.toml --no-default-features --features "crypto_pure_rust" -- --nocapture
