workspace: "/tmp/"
debs:
  - apt-transport-https
  - ninja-build
  - libuv1-dev
  - libc++-10-dev
  - libc++abi-10-dev
  - python3.8-dev
  - python3.8-venv
  - llvm-10
  - clang-10
  - clang-format-10
  - clang-tools-10
  - expect
  - git
  - ccache
  - doxygen
  - kmod
  - cmake
  - libssl-dev
  - jq
  - sudo
  - curl
  - shellcheck
  - iptables

mbedtls_ver: "2.16.8"
mbedtls_dir: "mbedtls-{{ mbedtls_ver }}"
mbedtls_src: "{{ mbedtls_dir }}.tar.gz"
