workspace: "/tmp/"
debs:
  - apt-transport-https
  - ninja-build
  - libuv1-dev
  - libc++-8-dev
  - libc++abi-8-dev
  - python3.7-dev
  - python3.7-venv
  - llvm-8
  - clang-8
  - clang-format-8
  - expect
  - xsltproc
  - git
  - libcurl4-openssl-dev
  - ccache
  - doxygen
  - kmod
  - cmake
  - libssl-dev
  - jq

mbedtls_ver: "2.16.6"
mbedtls_dir: "mbedtls-{{ mbedtls_ver }}"
mbedtls_src: "{{ mbedtls_dir }}.tar.gz"
fb_ver: "1.12.0"
flatbuffers_src: "v{{ fb_ver }}.tar.gz"
flatbuffers_url: "https://github.com/google/flatbuffers/archive/v{{ fb_ver }}.tar.gz"
fb_prefix: "/opt/flatbuffers"
step_cli_ver: "0.14.4"
step_cli: "https://github.com/smallstep/cli/releases/download/v{{ step_cli_ver }}/step-cli_{{ step_cli_ver }}_amd64.deb"