- hosts: localhost
  vars:
    oe_playbook: scripts/ansible/oe-contributors-acc-setup-no-driver.yml
    oe_build_opts: ""
  tasks:
    - import_role:
        name: intel
        tasks_from: sgx-psw.yml
    - import_role:
        name: intel
        tasks_from: sgx-psw-dev.yml
    - import_role:
        name: openenclave
        tasks_from: install.yml
    - import_role:
        name: llvm_repo
        tasks_from: install.yml
    - import_role:
        name: ccf_run
        tasks_from: install.yml
    - import_role:
        name: ccf_build
        tasks_from: install.yml