- hosts: all
  vars:
    workspace: "/tmp/"
    oe_ver: "0.6.0"
    oe_src: "oe-{{ oe_ver }}.tar.gz"
    oe_prefix: "/opt/openenclave-{{ oe_ver }}"
    everest_ver: "mbedtls-snapshot-7"

  tasks:

  - name: Download OpenEnclave source
    get_url:
      url: https://github.com/openenclave/openenclave/tarball/7b4acfbb72c11a3c692ac232414f22f685d2db39
      dest: "{{ workspace }}/{{ oe_src }}"
      force: yes
    become: true

  - name: Remove Pre-existing OpenEnclave source on the remote
    file:
      path: "{{ workspace }}/openenclave-{{ oe_ver }}"
      state: absent

  - name: Create directory for OpenEnclave source
    file:
      path: "{{ workspace }}/openenclave-{{ oe_ver }}"
      state: directory

  - name: Expand OpenEnclave
    unarchive:
      src: "{{ workspace }}/{{ oe_src }}"
      dest: "{{ workspace }}/openenclave-{{ oe_ver }}"
      copy: no
      extra_opts: [--strip-components=1]
      creates: "{{ workspace }}/openenclave-{{ oe_ver }}/CMakeLists.txt"

  - name: Make OpenEnclave build dir
    file:
      path: "{{ workspace }}/openenclave-{{ oe_ver }}/build"
      state: directory

  - name: Install OpenEnclave dependencies
    shell: |
      scripts/ansible/install-ansible.sh
      ansible-playbook "{{ oe_playbook }}"
    args:
      chdir: "{{ workspace }}/openenclave-{{ oe_ver }}"
    become: true
    async: 600
    poll: 5
    when: skip_dependencies is undefined

  - name: Install ninja
    apt:
      name: ninja-build
    become: true

  - name: Make OpenEnclave build dir
    file:
      path: "{{ workspace }}/openenclave-{{ oe_ver }}/build"
      state: directory

  - name: Build OpenEnclave
    shell: |
      cmake -GNinja -DCMAKE_INSTALL_PREFIX:PATH={{ oe_prefix }} -DCMAKE_BUILD_TYPE=RelWithDebInfo {{ oe_build_opts }} ..
      ninja
    args:
      chdir: "{{ workspace }}/openenclave-{{ oe_ver }}/build"
    async: 600
    poll: 5

  - name: Remove Pre-existing OpenEnclave install
    file:
      path: "{{ oe_prefix }}"
      state: absent
    become: true

  - name: Install OpenEnclave
    command: ninja install
    args:
      chdir: "{{ workspace }}/openenclave-{{ oe_ver }}/build"
    become: true
