graph LR
    crypto -.-> ds
    tls --> crypto
    tls --> ds
    ds -.-> crypto
    ds -.-> http
    ds -.-> kv
    ds -.-> node
    js --> ds
    js -.-> enclave
    js --> kv
    js -.-> node
    common --> consensus
    common --> crypto
    common --> ds
    common --> enclave
    common -.-> node
    http --> crypto
    http -.-> ds
    http -.-> enclave
    http -.-> node
    indexing --> crypto
    indexing --> ds
    indexing --> kv
    indexing -.-> node
    apps --> ds
    apps --> enclave
    apps --> http
    apps --> kv
    apps --> node
    clients --> crypto
    clients --> ds
    clients --> http
    clients --> node
    clients --> tls
    consensus --> crypto
    consensus --> ds
    consensus --> enclave
    consensus -.-> kv
    consensus -.-> node
    kv -.-> consensus
    kv --> crypto
    kv -.-> ds
    kv --> enclave
    kv -.-> node
    enclave --> crypto
    enclave --> ds
    enclave -.-> http
    enclave --> indexing
    enclave -.-> js
    enclave -.-> node
    enclave --> tls
    host --> common
    host --> consensus
    host --> crypto
    host --> ds
    host --> enclave
    host --> kv
    host --> node
    host --> tls
    node -.-> common
    node -.-> consensus
    node --> crypto
    node -.-> ds
    node -.-> enclave
    node -.-> http
    node -.-> indexing
    node -.-> js
    node -.-> kv
    node --> tls