# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache 2.0 License.
# 
# # -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x03\x63\x63\x66\x1a\x19google/protobuf/any.proto\"\x17\n\x04Test\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2<\n\x04\x45\x63ho\x12\x34\n\x04\x45\x63ho\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x62\x06proto3')



_TEST = DESCRIPTOR.message_types_by_name['Test']
Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'echo_pb2'
  # @@protoc_insertion_point(class_scope:ccf.Test)
  })
_sym_db.RegisterMessage(Test)

_ECHO = DESCRIPTOR.services_by_name['Echo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEST._serialized_start=46
  _TEST._serialized_end=69
  _ECHO._serialized_start=71
  _ECHO._serialized_end=131
# @@protoc_insertion_point(module_scope)
