jobs:
- job: Checks
  displayName: 'Formatting, License and Lint Checks'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
      submodules: true

    - script: ./scripts/ci-checks.sh
      displayName: 'Checks'
      condition: succeededOrFailed()