steps:
- script: mkdir build
  displayName: 'Make build dir'

- script: ./cimetrics_env.sh python -m cimetrics.plot
  env:
    METRICS_MONGO_CONNECTION: $(METRICS_MONGO_CONNECTION)
  workingDirectory: build
  displayName: 'Plot cimetrics'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- script: ./cimetrics_env.sh python -m cimetrics.github_pr
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  workingDirectory: build
  displayName: 'Post cimetrics graphs as PR comment'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: _cimetrics
    artifactName: cimetrics
  displayName: 'Publish cimetrics graphs as build artifact'
  condition: eq(variables['Build.Reason'], 'PullRequest')