jobs:
- job: Build_${{ parameters.target }}_${{ parameters.consensus }}
  displayName: 'Build ${{ parameters.target }} ${{ parameters.consensus }}'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: build.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }} -DBUILD_SMALLBANK=OFF'
    - template: publish_build.yml
      parameters:
        artifact_name: build_results_${{ parameters.target }}_${{ parameters.consensus }}

- job: Tests_${{ parameters.target }}_${{ parameters.consensus }}
  displayName: 'UnitTests ${{ parameters.target }} ${{ parameters.consensus }}'

  ${{ insert }}: ${{ parameters.env }}

  dependsOn:
    - Build_${{ parameters.target }}_${{ parameters.consensus }}

  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: download_build.yml
      parameters:
        artifact_name: build_results_${{ parameters.target }}_${{ parameters.consensus }}
    - template: test.yml
      parameters:
        ctest_filter: '-LE "benchmark|perf"'
        suite_name_suffix: '${{ parameters.target }} ${{ parameters.consensus }} tests'