jobs:
- job: Build_${{ parameters.target }}_${{ parameters.consensus }}

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/build.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'