jobs:
- job: BuildAndTest_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.protocol }}_${{ parameters.suffix }}
  variables:
    skipComponentGovernanceDetection: true
  displayName: 'Build and Test ${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.protocol }} ${{ parameters.suffix }}'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
    - template: cmake.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
        suite_label_suffix: '${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.protocol }}'
    - template: ninja.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
    - template: test.yml
      parameters:
        ctest_filter: ${{ parameters.ctest_filter }}
        suite_name_suffix: '${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.protocol }} ${{ parameters.suffix }} tests'
    - ${{ if and(eq(parameters.target, 'NoSGX'), eq(parameters.suffix, '')) }}:
      - template: coverage.yml
        parameters:
          consensus: ${{ parameters.consensus }}
    - ${{ if eq(parameters.suffix, 'Perf') }}:
      - template: push_perf_data.yml
        parameters:
          consensus: ${{ parameters.consensus }}
    - ${{ if eq(parameters.suffix, 'Release') }}:
      - template: install.yml
        parameters:
          protocol: ${{ parameters.protocol }}
          install_prefix: ${{ parameters.install_prefix }}