jobs:
- job: Test_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}
  variables:
    skipComponentGovernanceDetection: true
  displayName: 'Test ${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }}'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - template: download_build.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}
    - template: test.yml
      parameters:
        ctest_filter: ${{ parameters.ctest_filter }}
        suite_name_suffix: '${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }} tests'
    - ${{ if and(eq(parameters.target, 'NoSGX'), eq(parameters.suffix, 'Debug')) }}:
      - template: coverage.yml
        parameters:
          consensus: ${{ parameters.consensus }}
    - ${{ if eq(parameters.suffix, 'Perf') }}:
      - template: push_perf_data.yml
        parameters:
          consensus: ${{ parameters.consensus }}
    - ${{ if and(ne(parameters.consensus, 'BFT'), eq(parameters.suffix, 'Release')) }}:
      - template: install.yml
        parameters:
          install_prefix: ${{ parameters.install_prefix }}