jobs:
- job: Build_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}
  displayName: 'Build ${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }}'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: build.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
    - template: publish_build.yml
      parameters:
        artifact_name: build_results_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}

- job: Tests_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}
  displayName: 'Tests ${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }}'

  ${{ insert }}: ${{ parameters.env }}

  dependsOn:
    - Build_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}

  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: download_build.yml
      parameters:
        artifact_name: build_results_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}
    - template: test.yml
      parameters:
        ctest_filter: ${{ parameters.ctest_filter }}
        suite_name_suffix: '${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }} tests'