jobs:
- job: ${{ parameters.target }}_${{ parameters.suffix }}
  variables:
    skipComponentGovernanceDetection: true
  displayName: '${{ parameters.target }} ${{ parameters.suffix }}'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
    - template: cmake.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
        suite_label_suffix: '${{ parameters.target }}'
    - template: ninja.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
    - template: publish_build.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}