jobs:
- job: BuildAndTest_${{ parameters.target }}_${{ parameters.consensus }}_${{ parameters.suffix }}
  variables:
    skipComponentGovernanceDetection: true
  displayName: 'Build and Test ${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }}'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
    - ${{ if eq(parameters.suffix, 'Perf') }}:  
      - template: unpack.yml
    - template: cmake.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
        suite_label_suffix: '${{ parameters.target }}_${{ parameters.consensus }}'
    - ${{ if ne(parameters.suffix, 'Perf') }}:  
      - template: ninja.yml
        parameters:
          cmake_args: '${{ parameters.cmake_args }}'
    - template: test.yml
      parameters:
        ctest_filter: ${{ parameters.ctest_filter }}
        suite_name_suffix: '${{ parameters.target }} ${{ parameters.consensus }} ${{ parameters.suffix }} tests'
    - ${{ if eq(parameters.suffix, 'Debug') }}:
      - template: coverage.yml
        parameters:
          consensus: ${{ parameters.consensus }}
    - ${{ if eq(parameters.suffix, 'Perf') }}:
      - template: push_perf_data.yml
        parameters:
          consensus: ${{ parameters.consensus }}
    - ${{ if eq(parameters.suffix, 'Release') }}:
      - template: install.yml
        parameters:
          install_prefix: ${{ parameters.install_prefix }}