steps:
- script: |
    sudo chmod a+w /opt
    ninja install
    cmake -L .. 2>/dev/null | grep CMAKE_INSTALL_PREFIX: | cut -d = -f 2 > /tmp/install_prefix
  workingDirectory: build
  displayName: 'Install'

- script: |
    ./test_install.sh
  displayName: Test installed CCF

- script: |
    INSTALL_PREFIX=`cat /tmp/install_prefix`
    cp -r /opt/openenclave $INSTALL_PREFIX
  displayName: Copy OE into install dir

- script: |
    INSTALL_PREFIX=`cat /tmp/install_prefix`
    tar czf $(Build.ArtifactStagingDirectory)/ccf.tar.gz ${INSTALL_PREFIX##/opt/}
  displayName: Create release tarball
  workingDirectory: /opt

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)/ccf.tar.gz
    artifact: ccf.tar.gz
    displayName: 'Publish CCF Install'