parameters:
  consensus: ['CFT', 'BFT']
  target: ['NoSGX', 'SGX']

  env:
    Checks:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
    Build_NoSGX:
      container: nosgx
      pool:  Ubuntu-1804-D8s_v3
      dependsOn: ['Formatting_and_License_Checks']
    NoSGX:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
      dependsOn: ['Formatting_and_License_Checks', 'Build_NoSGX_Debug']
    Build_SGX:
      container: sgx
      pool: Ubuntu-1804-DC8_v2
      dependsOn: ['Formatting_and_License_Checks']
    SGX:
      container: sgx
      pool: Ubuntu-1804-DC8_v2
      dependsOn: ['Formatting_and_License_Checks', 'Build_SGX_Debug']
    Build_SAN:
      container: nosgx
      pool: Ubuntu-1804-D16s_v3
      dependsOn: ['Formatting_and_License_Checks']
    SAN:
      container: nosgx
      pool: Ubuntu-1804-D16s_v3
      dependsOn: ['Formatting_and_License_Checks', 'Build_NoSGX_SAN']
    Release:
      container: sgx
      pool: Ubuntu-1804-DC4s
      dependsOn: ['Test_NoSGX_CFT_Debug', 'Test_SGX_CFT_Debug', 'Test_NoSGX_CFT_SAN', 'Test_NoSGX_BFT_Debug', 'Test_SGX_BFT_Debug', 'Test_NoSGX_BFT_SAN']
    Metrics:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
      dependsOn: ['Test_SGX_CFT_Perf', 'Test_SGX_BFT_Perf']
    Publish:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
      dependsOn: ['Test_SGX_CFT_Release', 'Test_SGX_BFT_Release']
    Build_Perf:
      pool: CCF-Perf
      dependsOn:  ['Formatting_and_License_Checks']
    Perf:
      pool: CCF-Perf
      dependsOn:  ['Build_SGX_Perf']

  build:
    common:
      cmake_args: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache"'
    NoSGX:
      cmake_args: '-DTARGET=virtual -DCOVERAGE=ON'
    SGX:
      cmake_args: ''
    debug:
      cmake_args: '-DCMAKE_BUILD_TYPE=Debug -DVERBOSE_LOGGING=ON -DBUILD_SMALLBANK=OFF'
    install:
      install_prefix: '/tmp/ccf-install'
      cmake_args: '-DCMAKE_INSTALL_PREFIX=/tmp/ccf-install'
    san:
      cmake_args: '-DSAN=ON'
    perf:
      cmake_args: '-DVERBOSE_LOGGING=ON -DDISTRIBUTE_PERF_TESTS="`../.nodes.sh`"'


  test:
    NoSGX:
      CFT:
        ctest_args: '-LE "benchmark|perf|suite|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|suite|raft|bench"'
    SGX:
      CFT:
        ctest_args: '-LE "benchmark|perf|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|raft|bench"'
    Release:
      ctest_args: '-LE "benchmark|perf"'
    perf:
      CFT:
        ctest_args: '-L "benchmark|perf" -LE "pbft"'
      BFT:
        ctest_args: '-L "perf" -LE "raft"'
    san:
      CFT:
        ctest_args: '-LE "benchmark|perf|suite|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|suite|raft|bench"'

jobs:
  - template: checks.yml
    parameters:
      env: ${{ parameters.env.Checks }}
      job_name: 'Formatting_and_License_Checks'
  
  - ${{ each target in parameters.target }}:
    - template: common_build.yml
      parameters:
        target: '${{ target }}'
        env: ${{ parameters.env[target] }}
        cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.debug.cmake_args }} ${{ parameters.build[target].cmake_args }}'
        suffix: 'Debug'
        artifact_name: 'Build_${{ target }}_Debug'

  # Debug test runs with code coverage
  - ${{ each target in parameters.target }}:
    - ${{ each consensus in parameters.consensus }}:
      - template: common_test.yml
        parameters:
          target: ${{ target }}
          consensus: ${{ consensus }}
          env: ${{ parameters.env[target] }}
          ctest_filter: '${{ parameters.test[target][consensus].ctest_args }}'
          suffix: 'Debug'
          artifact_name: 'Build_${{ target }}_Debug'

  # SAN build (ASAN & UBSAN)
  - template: common_build.yml
    parameters:
      target: Build_NoSGX
      env: ${{ parameters.env.Build_SAN }}
      cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.san.cmake_args }} ${{ parameters.build.NoSGX.cmake_args }}'
      suffix: 'SAN'
      artifact_name: 'Build_NoSGX_SAN'

  # SAN Tests
  - ${{ each consensus in parameters.consensus }}:
    - template: common_test.yml
      parameters:
        target: NoSGX
        consensus: ${{ consensus }}
        env: ${{ parameters.env.SAN }}
        ctest_filter: '${{ parameters.test.san[consensus].ctest_args }}'
        suffix: 'SAN'
        artifact_name: 'Build_NoSGX_SAN'

  # Performance build
  - template: common_build.yml
    parameters:
      target: Build_SGX
      env: ${{ parameters.env.Build_Perf }}
      cmake_args: '${{ parameters.build.SGX.cmake_args }} ${{ parameters.build.perf.cmake_args }}'
      suffix: 'Perf'
      artifact_name: 'Build_SGX_Perf'

  
  # Performance tests
  - ${{ each consensus in parameters.consensus }}:
      - template: common_test.yml
        parameters:
          target: SGX
          consensus: ${{ consensus }}
          env: ${{ parameters.env.Perf }}
          ctest_filter: '${{ parameters.test.perf[consensus].ctest_args }}'
          suffix: 'Perf'
          artifact_name: 'Build_SGX_Perf'

  # Collect and Plot metrics
  - template: metrics.yml
    parameters:
      env: ${{ parameters.env.Metrics }}

  # # Publish release
  # - ${{ if eq(parameters.perf_or_release, 'release') }}:
  #   # Release builds
  #   - ${{ each consensus in parameters.consensus }}:
  #     - template: common_test.yml
  #       parameters:
  #         target: SGX
  #         consensus: ${{ consensus }}
  #         env: ${{ parameters.env.Release }}
  #         install: true
  #         install_prefix: '${{ parameters.build.install.install_prefix }}'
  #         cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.install.cmake_args }} ${{ parameters.build.SGX.cmake_args }} ${{ parameters.build[consensus].cmake_args }}'
  #         ctest_filter: '${{ parameters.test.Release.ctest_args }}'
  #         suffix: 'Release'

  #   - template: release.yml
  #     parameters:
  #       env: ${{ parameters.env.Publish }}

