parameters:
  consensus: ['CFT', 'BFT']
  target: ['NoSGX', 'SGX']
  build_target: ['Build_NoSGX', 'Build_SGX']

  env:
    Checks:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
    Build_NoSGX:
      container: nosgx
      pool:  Ubuntu-1804-D8s_v3
      dependsOn: ['Formatting_and_License_Checks']
    NoSGX:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
      dependsOn: ['Formatting_and_License_Checks', 'Build_NoSGX_Debug']
    Build_SGX:
      container: sgx
      pool: Ubuntu-1804-DC8_v2
      dependsOn: ['Formatting_and_License_Checks']
    SGX:
      container: sgx
      pool: Ubuntu-1804-DC8_v2
      dependsOn: ['Formatting_and_License_Checks', 'Build_SGX_Debug']
    Build_SAN:
      container: nosgx
      pool: Ubuntu-1804-D16s_v3
      dependsOn: ['Formatting_and_License_Checks']
    SAN:
      container: nosgx
      pool: Ubuntu-1804-D16s_v3
      dependsOn: ['Formatting_and_License_Checks', 'Build_NoSGX_SAN']
    Build_Release:
      container: sgx
      pool: Ubuntu-1804-DC4s
      dependsOn: ['Test_NoSGX_CFT_Debug', 'Test_SGX_CFT_Debug', 'Test_NoSGX_CFT_SAN', 'Test_NoSGX_BFT_Debug', 'Test_SGX_BFT_Debug', 'Test_NoSGX_BFT_SAN']
    Release:
      container: sgx
      pool: Ubuntu-1804-DC4s
      dependsOn: ['Build_SGX_Release']
    Metrics:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
      dependsOn: ['Test_SGX_CFT_Perf', 'Test_SGX_BFT_Perf']
    Publish:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
      dependsOn: ['Test_SGX_CFT_Release', 'Test_SGX_BFT_Release']
    Build_Perf:
      pool: CCF-Perf
      dependsOn:  ['Formatting_and_License_Checks']
    Perf:
      pool: CCF-Perf
      dependsOn:  ['Build_SGX_Perf']

  build:
    Build_SGX: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DCMAKE_BUILD_TYPE=Debug -DVERBOSE_LOGGING=ON -DBUILD_SMALLBANK=OFF'
    Build_NoSGX: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DCMAKE_BUILD_TYPE=Debug -DVERBOSE_LOGGING=ON -DBUILD_SMALLBANK=OFF -DTARGET=virtual -DCOVERAGE=ON'
    SGX: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DCMAKE_BUILD_TYPE=Debug -DVERBOSE_LOGGING=ON -DBUILD_SMALLBANK=OFF'
    NoSGX: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DCMAKE_BUILD_TYPE=Debug -DVERBOSE_LOGGING=ON -DBUILD_SMALLBANK=OFF -DTARGET=virtual -DCOVERAGE=ON'
    san: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DSAN=ON -DTARGET=virtual -DCOVERAGE=ON'
    perf: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DVERBOSE_LOGGING=ON -DDISTRIBUTE_PERF_TESTS="`../.nodes.sh`"'
    install: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DCMAKE_INSTALL_PREFIX=/tmp/ccf-install -DCMAKE_INSTALL_PREFIX=/tmp/ccf-install'

  install:
    install_prefix: '/tmp/ccf-install'


  test:
    NoSGX:
      CFT:
        ctest_args: '-LE "benchmark|perf|suite|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|suite|raft"'
    SGX:
      CFT:
        ctest_args: '-LE "benchmark|perf|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|raft"'
    Release:
      CFT:
        ctest_args: '-LE "benchmark|perf|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|raft"'
    perf:
      CFT:
        ctest_args: '-L "benchmark|perf" -LE "pbft"'
      BFT:
        ctest_args: '-L "perf" -LE "raft"'
    san:
      CFT:
        ctest_args: '-LE "benchmark|perf|suite|pbft"'
      BFT:
        ctest_args: '-LE "benchmark|perf|suite|raft"'

jobs:
  - template: checks.yml
    parameters:
      env: ${{ parameters.env.Checks }}
      job_name: 'Formatting_and_License_Checks'
  
  - ${{ each build_target in parameters.build_target }}:
    - template: common_build.yml
      parameters:
        target: '${{ build_target }}'
        env: ${{ parameters.env[build_target] }}
        cmake_args: '${{ parameters.build[build_target] }}'
        suffix: 'Debug'
        artifact_name: '${{ build_target }}_Debug'

  # Debug test runs with code coverage
  - ${{ each target in parameters.target }}:
    - ${{ each consensus in parameters.consensus }}:
      - template: common_test.yml
        parameters:
          target: ${{ target }}
          consensus: ${{ consensus }}
          env: ${{ parameters.env[target] }}
          cmake_args: '${{ parameters.build[target] }}'
          ctest_filter: '${{ parameters.test[target][consensus].ctest_args }}'
          suffix: 'Debug'
          artifact_name: 'Build_${{ target }}_Debug'

  # SAN build (ASAN & UBSAN)
  - template: common_build.yml
    parameters:
      target: Build_NoSGX
      env: ${{ parameters.env.Build_SAN }}
      cmake_args: '${{ parameters.build.san }}'
      suffix: 'SAN'
      artifact_name: 'Build_NoSGX_SAN'

  # SAN Tests
  - ${{ each consensus in parameters.consensus }}:
    - template: common_test.yml
      parameters:
        target: NoSGX
        consensus: ${{ consensus }}
        env: ${{ parameters.env.SAN }}
        cmake_args: '${{ parameters.build.san }}'
        ctest_filter: '${{ parameters.test.san[consensus].ctest_args }}'
        suffix: 'SAN'
        artifact_name: 'Build_NoSGX_SAN'

  # Performance build
  - template: common_build.yml
    parameters:
      target: Build_SGX
      env: ${{ parameters.env.Build_Perf }}
      cmake_args: '${{ parameters.build.perf }}'
      suffix: 'Perf'
      artifact_name: 'Build_SGX_Perf'

  
  # Performance tests
  - ${{ each consensus in parameters.consensus }}:
      - template: common_test.yml
        parameters:
          target: SGX
          consensus: ${{ consensus }}
          env: ${{ parameters.env.Perf }}
          install_prefix: '${{ parameters.install.install_prefix }}'
          cmake_args: '${{ parameters.build.perf }}'
          ctest_filter: '${{ parameters.test.perf[consensus].ctest_args }}'
          suffix: 'Perf'
          artifact_name: 'Build_SGX_Perf'

  # Collect and Plot metrics
  - template: metrics.yml
    parameters:
      env: ${{ parameters.env.Metrics }}

  # Publish release
  - ${{ if eq(parameters.perf_or_release, 'release') }}:
    # Release build
    - template: common_build.yml
      parameters:
        target: Build_SGX
        env: ${{ parameters.env.Build_Release }}
        cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.install.cmake_args }} ${{ parameters.build.SGX.cmake_args }}'
        suffix: 'Release'
        artifact_name: 'Build_SGX_Release'

    # Release builds
    - ${{ each consensus in parameters.consensus }}:
      - template: common_test.yml
        parameters:
          target: SGX
          consensus: ${{ consensus }}
          env: ${{ parameters.env.Release }}
          install_prefix: '${{ parameters.build.install.install_prefix }}'
          cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.install.cmake_args }} ${{ parameters.build.SGX.cmake_args }}'
          ctest_filter: '${{ parameters.test.Release[consensus].ctest_args }}'
          suffix: 'Release'
          artifact_name: 'Build_SGX_Release'

    - template: release.yml
      parameters:
        env: ${{ parameters.env.Publish }}

