jobs:
- job: GitHubRelease
  variables:
    skipComponentGovernanceDetection: true
  displayName: 'GitHub Release'
  dependsOn: ${{ parameters.depends_on }}

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        patterns: '**/ccf*.tar.gz'
        path: $(Build.ArtifactStagingDirectory)

    - task: GitHubRelease@0
      inputs:
        gitHubConnection: ccf_release
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'auto'
        assets: $(Build.ArtifactStagingDirectory)/**/ccf.tar.gz
        assetUploadMode: 'delete'
        isDraft: true
        isPreRelease: true
        addChangeLog: false
      displayName: 'GitHub release (create)'

    # For now, push to test PyPi
    - script: |
        python3.7 -m venv env
        source ./env/bin/activate
        python setup.py sdist
        python -m pip install twine
        twine upload -u __token__ -p $(pypi_test_token) --repository testpypi dist/*
      workingDirectory: python
      displayName: PyPi https://test.pypi.org/project/ccf/