var searchData=
[
  ['raftheader_0',['RaftHeader',['../structaft_1_1RaftHeader.html',1,'aft']]],
  ['raftheader_3c_20raft_5fappend_5fentries_20_3e_1',['RaftHeader&lt; raft_append_entries &gt;',['../structaft_1_1RaftHeader.html',1,'aft']]],
  ['raftheader_3c_20raft_5fappend_5fentries_5fresponse_20_3e_2',['RaftHeader&lt; raft_append_entries_response &gt;',['../structaft_1_1RaftHeader.html',1,'aft']]],
  ['raftheader_3c_20raft_5fpropose_5frequest_5fvote_20_3e_3',['RaftHeader&lt; raft_propose_request_vote &gt;',['../structaft_1_1RaftHeader.html',1,'aft']]],
  ['raftheader_3c_20raft_5frequest_5fvote_20_3e_4',['RaftHeader&lt; raft_request_vote &gt;',['../structaft_1_1RaftHeader.html',1,'aft']]],
  ['raftheader_3c_20raft_5frequest_5fvote_5fresponse_20_3e_5',['RaftHeader&lt; raft_request_vote_response &gt;',['../structaft_1_1RaftHeader.html',1,'aft']]],
  ['rawreader_6',['RawReader',['../classkv_1_1RawReader.html',1,'kv']]],
  ['rawsection_7',['RawSection',['../structserializer_1_1RawSection.html',1,'serializer']]],
  ['rawwriter_8',['RawWriter',['../classkv_1_1RawWriter.html',1,'kv']]],
  ['readablemaphandle_9',['ReadableMapHandle',['../classkv_1_1ReadableMapHandle.html',1,'kv']]],
  ['readablesethandle_10',['ReadableSetHandle',['../classkv_1_1ReadableSetHandle.html',1,'kv']]],
  ['readablevaluehandle_11',['ReadableValueHandle',['../classkv_1_1ReadableValueHandle.html',1,'kv']]],
  ['reader_12',['Reader',['../classringbuffer_1_1Reader.html',1,'ringbuffer']]],
  ['readonlyendpointcontext_13',['ReadOnlyEndpointContext',['../structccf_1_1endpoints_1_1ReadOnlyEndpointContext.html',1,'ccf::endpoints']]],
  ['readonlystore_14',['ReadOnlyStore',['../classkv_1_1ReadOnlyStore.html',1,'kv']]],
  ['readonlytx_15',['ReadOnlyTx',['../classkv_1_1ReadOnlyTx.html',1,'kv']]],
  ['receipt_16',['Receipt',['../classccf_1_1Receipt.html',1,'ccf']]],
  ['receivedreply_17',['ReceivedReply',['../structtiming_1_1ReceivedReply.html',1,'timing']]],
  ['recover_18',['Recover',['../structhost_1_1CCHostConfig_1_1Command_1_1Recover.html',1,'host::CCHostConfig::Command::Recover'],['../structStartupConfig_1_1Recover.html',1,'StartupConfig::Recover']]],
  ['recoverysharesinfo_19',['RecoverySharesInfo',['../structccf_1_1RecoverySharesInfo.html',1,'ccf']]],
  ['redirectionresolverconfig_20',['RedirectionResolverConfig',['../structccf_1_1RedirectionResolverConfig.html',1,'ccf']]],
  ['redirections_21',['Redirections',['../structccf_1_1NodeInfoNetwork__v2_1_1NetInterface_1_1Redirections.html',1,'ccf::NodeInfoNetwork_v2::NetInterface']]],
  ['refreshtimemsg_22',['RefreshTimeMsg',['../structccf_1_1JwtKeyAutoRefresh_1_1RefreshTimeMsg.html',1,'ccf::JwtKeyAutoRefresh']]],
  ['replica_23',['Replica',['../classaft_1_1Replica.html',1,'aft']]],
  ['replicatednetworkidentity_24',['ReplicatedNetworkIdentity',['../classccf_1_1ReplicatedNetworkIdentity.html',1,'ccf']]],
  ['request_25',['Request',['../structccf_1_1historical_1_1StateCacheImpl_1_1Request.html',1,'ccf::historical::StateCacheImpl::Request'],['../classhttp_1_1Request.html',1,'http::Request'],['../structhttp_1_1SimpleRequestProcessor_1_1Request.html',1,'http::SimpleRequestProcessor::Request']]],
  ['requestcallbackargs_26',['RequestCallbackArgs',['../structkv_1_1TxHistory_1_1RequestCallbackArgs.html',1,'kv::TxHistory']]],
  ['requestheadertoolargeexception_27',['RequestHeaderTooLargeException',['../classhttp_1_1RequestHeaderTooLargeException.html',1,'http']]],
  ['requestparser_28',['RequestParser',['../classhttp_1_1RequestParser.html',1,'http']]],
  ['requestpayloadtoolargeexception_29',['RequestPayloadTooLargeException',['../classhttp_1_1RequestPayloadTooLargeException.html',1,'http']]],
  ['requestprocessor_30',['RequestProcessor',['../classhttp_1_1RequestProcessor.html',1,'http']]],
  ['requesttoolargeexception_31',['RequestTooLargeException',['../classhttp_1_1RequestTooLargeException.html',1,'http']]],
  ['requestvote_32',['RequestVote',['../structaft_1_1RequestVote.html',1,'aft']]],
  ['requestvoteresponse_33',['RequestVoteResponse',['../structaft_1_1RequestVoteResponse.html',1,'aft']]],
  ['reservation_34',['Reservation',['../structringbuffer_1_1Writer_1_1Reservation.html',1,'ringbuffer::Writer']]],
  ['reservedtx_35',['ReservedTx',['../classkv_1_1ReservedTx.html',1,'kv']]],
  ['resettcpreadquotaimpl_36',['ResetTCPReadQuotaImpl',['../classasynchost_1_1ResetTCPReadQuotaImpl.html',1,'asynchost']]],
  ['resetudpreadquotaimpl_37',['ResetUDPReadQuotaImpl',['../classasynchost_1_1ResetUDPReadQuotaImpl.html',1,'asynchost']]],
  ['responderlookup_38',['ResponderLookup',['../classhttp_1_1ResponderLookup.html',1,'http']]],
  ['response_39',['Response',['../structclient_1_1HttpRpcTlsClient_1_1Response.html',1,'client::HttpRpcTlsClient::Response'],['../classhttp_1_1Response.html',1,'http::Response'],['../structhttp_1_1SimpleResponseProcessor_1_1Response.html',1,'http::SimpleResponseProcessor::Response']]],
  ['responsecallbackargs_40',['ResponseCallbackArgs',['../structkv_1_1TxHistory_1_1ResponseCallbackArgs.html',1,'kv::TxHistory']]],
  ['responseparser_41',['ResponseParser',['../classhttp_1_1ResponseParser.html',1,'http']]],
  ['responseprocessor_42',['ResponseProcessor',['../classhttp_1_1ResponseProcessor.html',1,'http']]],
  ['responsetimes_43',['ResponseTimes',['../classtiming_1_1ResponseTimes.html',1,'timing']]],
  ['restverb_44',['RESTVerb',['../classccf_1_1RESTVerb.html',1,'ccf']]],
  ['resultcallbackargs_45',['ResultCallbackArgs',['../structkv_1_1TxHistory_1_1ResultCallbackArgs.html',1,'kv::TxHistory']]],
  ['results_46',['Results',['../structtiming_1_1Results.html',1,'timing']]],
  ['retirednodecleanup_47',['RetiredNodeCleanup',['../classccf_1_1RetiredNodeCleanup.html',1,'ccf']]],
  ['retirednodecleanupmsg_48',['RetiredNodeCleanupMsg',['../structccf_1_1RetiredNodeCleanup_1_1RetiredNodeCleanupMsg.html',1,'ccf::RetiredNodeCleanup']]],
  ['ringbufferlogger_49',['RingbufferLogger',['../classccf_1_1RingbufferLogger.html',1,'ccf']]],
  ['roll_50',['Roll',['../structkv_1_1untyped_1_1Roll.html',1,'kv::untyped']]],
  ['rpcconnections_51',['RPCConnections',['../classasynchost_1_1RPCConnections.html',1,'asynchost']]],
  ['rpccontext_52',['RpcContext',['../classccf_1_1RpcContext.html',1,'ccf']]],
  ['rpccontextimpl_53',['RpcContextImpl',['../classccf_1_1RpcContextImpl.html',1,'ccf']]],
  ['rpcexception_54',['RpcException',['../structccf_1_1RpcException.html',1,'ccf']]],
  ['rpcfrontend_55',['RpcFrontend',['../classccf_1_1RpcFrontend.html',1,'ccf']]],
  ['rpchandler_56',['RpcHandler',['../classccf_1_1RpcHandler.html',1,'ccf']]],
  ['rpcmap_57',['RPCMap',['../classccf_1_1RPCMap.html',1,'ccf']]],
  ['rpcsessions_58',['RPCSessions',['../classccf_1_1RPCSessions.html',1,'ccf']]],
  ['rsakeypair_59',['RSAKeyPair',['../classcrypto_1_1RSAKeyPair.html',1,'crypto']]],
  ['rsakeypair_5fopenssl_60',['RSAKeyPair_OpenSSL',['../classcrypto_1_1RSAKeyPair__OpenSSL.html',1,'crypto']]],
  ['rsapublickey_61',['RSAPublicKey',['../classcrypto_1_1RSAPublicKey.html',1,'crypto']]],
  ['rsapublickey_5fopenssl_62',['RSAPublicKey_OpenSSL',['../classcrypto_1_1RSAPublicKey__OpenSSL.html',1,'crypto']]],
  ['runtime_63',['Runtime',['../classccf_1_1js_1_1Runtime.html',1,'ccf::js']]]
];
