trigger: none

variables:
- template: /.pipelines/variables.yml@self

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    cloudvault:
      enabled: false
    globalSdl:
      perStage:
        sdl_sources:
          checkout_all_repos: true
      tsa:
        enabled: false
      policheck:
        break: true
      codeql:
        compiled:
          enabled: true
    stages:
    - template: /.pipelines/common.yml@self
      parameters:
        IsOfficialBuild: false
