-------------------------------- MODULE TraceMultiNodeReads -------------------------------
EXTENDS MultiNodeReads, Json, IOUtils, Sequences, SequencesExt

\* Trace validation has been designed for TLC running in default model-checking
\* mode, i.e., breadth-first search.
\* The property TraceMatched will be violated if TLC runs with more than a single worker.
ASSUME TLCGet("config").mode = "bfs" /\ TLCGet("config").worker = 1

\* Note the extra /../ necessary to run in the VSCode extension but not a happy CLI default
JsonFile ==
    IF "JSON" \in DOMAIN IOEnv THEN IOEnv.JSON ELSE "../../build/consistency/trace.ndjson"

JsonLog ==
    \* Deserialize the System log as a sequence of records from the log file.
    \* Run TLC from under the tla/ directory with:
    \* $ JSON=../build/consistency/trace.ndjson ./tlc.sh consistency/TraceMultiNodeReads.tla
    \* Traces can be generated by running ./tests.sh -VV -R consistency_trace_validation under build/
    \* The clients execute transactions sequentially, and so the log is ordered by tx
    ndJsonDeserialize(JsonFile)

VARIABLE l

TraceInit ==
    /\ l = 1
    /\ Init

logline ==
    JsonLog[l]

ToTxType ==
    "RwTxRequest" :> RwTxRequest @@
    "RwTxResponse" :>  RwTxResponse @@
    "TxStatusReceived" :> TxStatusReceived @@
    "RoTxRequest" :> RoTxRequest @@
    "RoTxResponse" :>  RoTxResponse

ToStatus ==
    "CommittedStatus" :> CommittedStatus @@
    "InvalidStatus" :>  InvalidStatus

\* Beware to only prime e.g. inbox in inbox'[rcv] and *not* also rcv, i.e.,
 \* inbox[rcv]'.  rcv is defined in terms of TLCGet("level") that correctly
 \* handles priming, which causes rcv' to equal rcv of the next log line.
IsEvent(e) ==
    \* Equals FALSE if we get past the end of the log, causing model checking to stop.
    /\ l \in 1..Len(JsonLog)
    /\ logline.action = e
    /\ l' = l + 1

IsRwTxRequestAction ==
    /\ IsEvent("RwTxRequestAction")
    /\ RwTxRequestAction
    /\ Last(history').type = ToTxType[logline.type]
    /\ Last(history').tx = logline.tx

IsRwTxExecuteAction ==
    /\ IsEvent("RwTxExecuteAction")
    /\ RwTxExecuteAction
    /\ Last(history').tx = logline.tx
    \* RwTxExecuteAction can only take place if a branch exists for the view
    /\ Len(ledgerBranches) >= logline.tx_id[1]
    \* and that branch contains just the right amount of transactions (seqno - 1)
    /\ Len(ledgerBranches[logline.tx_id[1]]) = logline.tx_id[2] - 1

IsRwTxResponseAction ==
    /\ IsEvent("RwTxResponseAction")
    /\ RwTxResponseAction
    /\ Last(history').type = ToTxType[logline.type]
    /\ Last(history').tx = logline.tx
    /\ Last(history').tx_id = logline.tx_id

IsStatusCommittedResponseAction ==
    /\ IsEvent("StatusCommittedResponseAction")
    /\ StatusCommittedResponseAction
    /\ Last(history').type = ToTxType[logline.type]
    /\ Last(history').status = ToStatus[logline.status]
    /\ Last(history').tx_id = logline.tx_id

IsRoTxRequestAction ==
    /\ IsEvent("RoTxRequestAction")
    /\ RoTxRequestAction
    /\ Last(history').type = ToTxType[logline.type]
    /\ Last(history').tx = logline.tx

IsRoTxResponseAction ==
    /\ IsEvent("RoTxResponseAction")
    /\ RoTxResponseAction
    /\ Last(history').type = ToTxType[logline.type]
    \* RwTxExecuteAction can only take place if a branch exists for the view
    /\ Len(ledgerBranches) >= logline.tx_id[1]
    \* and that branch contains just the right amount of transactions (seqno - 1)
    /\ Len(ledgerBranches[logline.tx_id[1]]) = logline.tx_id[2] - 1

IsStatusInvalidResponseAction ==
    /\ IsEvent("StatusInvalidResponseAction")
    \* Cannot use StatusInvalidResponseAction directly, as it requires knowledge
    \* of an incompatible history state, which is not available at this point in the trace.
    /\ LET view == logline.tx_id[1]
           seqno == logline.tx_id[2]
       IN /\ Len(ledgerBranches[view]) < seqno 
          /\ history' = Append(
             history, [
                type |-> ToTxType[logline.type],
                tx_id |-> logline.tx_id,
                status |-> ToStatus[logline.status]
             ]
            )
    /\ UNCHANGED <<ledgerBranches>>

\* Matches an event, but without advancing the log line. Useful to apply changes
\* before an event can be handled, for example backfilling the ledger branch, or
\* creating new ledger branches.
PreEvent(e) ==
    /\ l' = l
    /\ l \in 1..Len(JsonLog)
    /\ logline.action = e

BackfillLedgerBranch ==
    /\
        \/ PreEvent("RwTxExecuteAction")
        \* There is no separate RoTxExecuteAction, but conceptually,
        \* we would backfill before it as well. Instead we do before the
        \* RoTxResponseAction, which is the earliest possible opportunity.
        \/ PreEvent("RoTxResponseAction")
    \* Similar to AppendOtherTxnAction, but only append to the specific branch
    \* necessary to enable the next transaction to execute.
    /\ LET view == logline.tx_id[1]
           seqno == logline.tx_id[2]
       IN /\ Len(ledgerBranches) >= view
          /\ Len(ledgerBranches[view]) < seqno - 1
          /\ ledgerBranches' = [ledgerBranches EXCEPT ![view] = Append(@, [view |-> view])]
    /\ UNCHANGED history

\* Same idead as BackfillLedgerBranch, but creating new ledger branches
\* when transaction execution takes place on a hitherto unseen view.
ViewChange ==
    /\
        \/ PreEvent("RwTxExecuteAction")
        \/ PreEvent("RoTxResponseAction")
    /\ LET view == logline.tx_id[1]
           seqno == logline.tx_id[2]
           newView == Len(ledgerBranches) + 1
       IN /\ Len(ledgerBranches) > view
          \* Conservative, always includes full uncommitted suffix from previous branch
          \* May be something to revisit, but avoids dropping seqnos that may later commit.
          /\ ledgerBranches' = [ledgerBranches EXCEPT ![newView] = Last(ledgerBranches)]
    /\ UNCHANGED history

\* 

\* Similar to TransactionRollback, but only roll back the specific branch necessary, and the
\* least amount necessary to invalidate the transaction. This is also conservative,
\* but it is not possible to know exactly how far along the commit is at this point from the trace alone.
RollbackLedgerBranch ==
    /\ PreEvent("StatusInvalidResponseAction")
    /\ LET view == logline.tx_id[1]
           seqno == logline.tx_id[2]
       IN /\ Len(ledgerBranches[view]) >= seqno
          /\ ledgerBranches' = [ledgerBranches EXCEPT ![view] = SubSeq(ledgerBranches[view], 1, seqno - 1)]
    /\ UNCHANGED history

TraceNext ==
    \/ IsRwTxRequestAction
    \/ IsRwTxExecuteAction
    \/ IsRwTxResponseAction
    \/ IsStatusCommittedResponseAction
    \/ IsRoTxRequestAction
    \/ IsRoTxResponseAction
    \/ IsStatusInvalidResponseAction
    \/ BackfillLedgerBranch
    \* That does not work because of LedgersMonoProp
    \* \/ RollbackLedgerBranch
    \* \/ ViewChange

TraceSpec ==
    TraceInit /\ [][TraceNext]_<<l, vars>>

-------------------------------------------------------------------------------------

Termination ==
    l = Len(JsonLog) => TLCSet("exit", TRUE)

-------------------------------------------------------------------------------------

TraceMatched ==
    \* We force TLC to check TraceMatched as a temporal property because TLC checks temporal
    \* properties after generating all successor states of the current state, unlike
    \* invariants that are checked after generating a successor state.
    \* If the queue is empty after generating all successors of the current state,
    \* and l is less than the length of the trace, then TLC failed to validate the trace.
    \*
    \* Note: Consider strengthening (Nat \ {0}) to {1} when validating traces with no nondeterminism.
    [](l <= Len(JsonLog) => [](TLCGet("queue") \in Nat \ {0} \/ l > Len(JsonLog)))

TraceMatchedNonTrivially ==
    \* If, e.g., the FALSE state constraint excludes all states, TraceMatched won't be violated.
    TLCGet("stats").diameter >= Len(JsonLog)

MNR == INSTANCE MultiNodeReads

MNRSpec == MNR!SpecMultiNodeReads

==================================================================================
