parameters:
  cmake_args: ''
  artifact_name: ''

steps:
- task: CMake@1
  displayName: CMake
  inputs:
    cmakeArgs: '-GNinja .. ${{ parameters.cmake_args }}'

- script: ninja
  displayName: Ninja
  workingDirectory: build

- task: CopyFiles@2
  inputs:
    sourceFolder: build
    contents: |
      CTestTestfile.cmake
      cchost
      cchost.virtual
      genesisgenerator
      raft_driver
      *_test
      *_bench
      *client
      *.so
      json_schema
      merkle_mem
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: $(artifact_name)
    targetPath: $(Build.ArtifactStagingDirectory)