name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_TOKEN }}"
          # https://github.com/pascalgn/automerge-action#configuration
          MERGE_LABELS: "automerge,!wip"
          MERGE_METHOD: "squash"
          MERGE_REMOVE_LABELS: "automerge,wip,sync"
          MERGE_FORKS: true
          UPDATE_LABELS: "sync,!wip"
          UPDATE_METHOD: "merge"