name: "Build and Publish Release Containers"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build Containers"
    runs-on: ubuntu-latest
    steps:
      - name: Build App CI container
        run: docker build -f docker/app_ci . --build-arg="extra_vars=--extra-vars ccf_ver=$GITHUB_REF"
      - name: Build App Run container
        run: docker build -f docker/app_run . --build-arg="extra_vars=--extra-vars ccf_ver=$GITHUB_REF"