name: "Build and Publish Release Containers"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build Containers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build App CI container
        run: docker build -f docker/app_ci . --build-arg="extra_vars=--extra-vars ccf_ver=$GITHUB_REF" -t ccfciteam/ccf-app-ci:$GITHUB_REF
        
      - name: Build App Run container
        run: docker build -f docker/app_run . --build-arg="extra_vars=--extra-vars ccf_ver=$GITHUB_REF" -t ccfciteam/ccf-app-run:$GITHUB_REF

      - name: Log in
        run: docker login -u amchamay -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push App CI container
        run: docker push ccfciteam/ccf-app-ci:$GITHUB_REF

      - name: Build App Run container
        run: docker push ccfciteam/ccf-app-run:$GITHUB_REF